apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: ram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: blackicebird/2048
        ports:
        - containerPort: 4000
